version: "3.8"

services:
  backend:
    build: .
    container_name: mindseek-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mounts local files into the container
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
